version: '3.4'

services:
    regiView:
      image: parkseungchul/regiview:v1
      networks:
        - regi_net
      links:
        - regi:regi
      environment:
        - port=5000
        - ip=regi
      ports:
        - "8080:8080"

    regi:
      image: registry
      networks:
        - regi_net
      ports:
        - "5000:5000"

networks:
  regi_net: